import type { ContentSnapshot } from '../../src/features/content/contentTypes.js';

export const contentFixture: ContentSnapshot = {
  siteSetting: {
    name: 'Woodbrook Residents',
    location: 'Shankill',
    tagline: 'Local information',
    introduction: 'Welcome',
    contactEmail: 'hello@example.com',
  },
  updates: [],
  projects: [
    {
      documentId: 'project-1',
      title: 'Green space project',
      slug: 'green-space',
      category: 'Public realm',
      stage: 'Active',
      summary: 'Work is under way.',
      details: 'Project details.',
      updatedOn: '2026-08-20',
      nextStep: 'Review the next update.',
      sourceName: 'Test council source',
      sourceUrl: 'https://example.com/project',
      sourceReviewedOn: '2026-08-21',
      featured: true,
    },
  ],
  events: [],
  surveys: [],
  resources: [
    {
      documentId: 'resource-long',
      title: 'Tall health service',
      slug: 'tall-health-service',
      category: 'Health',
      serviceType: 'Health centre',
      providerType: 'Public service',
      description:
        'A health service with enough published detail that its record is much taller than one viewport. Residents can read opening hours, accessibility notes, contact channels, and service facts before visiting.',
      url: 'https://example.com/tall-health',
      phone: '012345678',
      email: 'tall-health@example.com',
      outOfHours: true,
      featured: true,
      details: [
        {
          id: 1,
          label: 'Hours',
          value: 'Monday to Friday, 9am to 5pm',
          showOnCard: true,
        },
        {
          id: 2,
          label: 'Accessibility',
          value: 'Step-free access and hearing loop',
          showOnCard: false,
        },
        {
          id: 3,
          label: 'Appointments',
          value: 'Book by phone or online',
          showOnCard: false,
        },
        {
          id: 4,
          label: 'Walk-ins',
          value: 'Walk-in clinic on Wednesday mornings',
          showOnCard: false,
        },
        {
          id: 5,
          label: 'Parking',
          value: 'Limited on-site parking with accessible bays',
          showOnCard: false,
        },
        {
          id: 6,
          label: 'Pharmacy',
          value: 'Dispensary beside the main entrance',
          showOnCard: false,
        },
        {
          id: 7,
          label: 'Out-of-hours contact',
          value: 'Call the out-of-hours number after 5pm',
          showOnCard: false,
        },
        {
          id: 8,
          label: 'Please note',
          value: 'Bring photo identification to your first visit',
          showOnCard: false,
        },
      ],
      collectionDates: [],
      displayOrder: 1,
      sourceName: 'HSE',
      sourceUrl: 'https://example.com/tall-health-source',
      sourceReviewedOn: '2026-09-09',
    },
  ],
};
