/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as LocalInfoIndexRouteImport } from './routes/local-info/index'
import { Route as LocalInfoSlugRouteImport } from './routes/local-info/$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as SurveysIndexRouteImport } from './routes/surveys/index'
import { Route as SurveysSlugRouteImport } from './routes/surveys/$slug'
import { Route as UpdatesIndexRouteImport } from './routes/updates/index'
import { Route as UpdatesSlugRouteImport } from './routes/updates/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalInfoIndexRoute = LocalInfoIndexRouteImport.update({
  id: '/local-info/',
  path: '/local-info/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalInfoSlugRoute = LocalInfoSlugRouteImport.update({
  id: '/local-info/$slug',
  path: '/local-info/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysIndexRoute = SurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysSlugRoute = SurveysSlugRouteImport.update({
  id: '/surveys/$slug',
  path: '/surveys/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesSlugRoute = UpdatesSlugRouteImport.update({
  id: '/updates/$slug',
  path: '/updates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-involved': typeof GetInvolvedRoute
  '/events/$slug': typeof EventsSlugRoute
  '/local-info/$slug': typeof LocalInfoSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/surveys/$slug': typeof SurveysSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/events/': typeof EventsIndexRoute
  '/local-info/': typeof LocalInfoIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/surveys/': typeof SurveysIndexRoute
  '/updates/': typeof UpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-involved': typeof GetInvolvedRoute
  '/events/$slug': typeof EventsSlugRoute
  '/local-info/$slug': typeof LocalInfoSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/surveys/$slug': typeof SurveysSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/events': typeof EventsIndexRoute
  '/local-info': typeof LocalInfoIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/surveys': typeof SurveysIndexRoute
  '/updates': typeof UpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get-involved': typeof GetInvolvedRoute
  '/events/$slug': typeof EventsSlugRoute
  '/local-info/$slug': typeof LocalInfoSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/surveys/$slug': typeof SurveysSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/events/': typeof EventsIndexRoute
  '/local-info/': typeof LocalInfoIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/surveys/': typeof SurveysIndexRoute
  '/updates/': typeof UpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-involved'
    | '/events/$slug'
    | '/local-info/$slug'
    | '/projects/$slug'
    | '/surveys/$slug'
    | '/updates/$slug'
    | '/events/'
    | '/local-info/'
    | '/projects/'
    | '/surveys/'
    | '/updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-involved'
    | '/events/$slug'
    | '/local-info/$slug'
    | '/projects/$slug'
    | '/surveys/$slug'
    | '/updates/$slug'
    | '/events'
    | '/local-info'
    | '/projects'
    | '/surveys'
    | '/updates'
  id:
    | '__root__'
    | '/'
    | '/get-involved'
    | '/events/$slug'
    | '/local-info/$slug'
    | '/projects/$slug'
    | '/surveys/$slug'
    | '/updates/$slug'
    | '/events/'
    | '/local-info/'
    | '/projects/'
    | '/surveys/'
    | '/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  EventsSlugRoute: typeof EventsSlugRoute
  LocalInfoSlugRoute: typeof LocalInfoSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  SurveysSlugRoute: typeof SurveysSlugRoute
  UpdatesSlugRoute: typeof UpdatesSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LocalInfoIndexRoute: typeof LocalInfoIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SurveysIndexRoute: typeof SurveysIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-info/': {
      id: '/local-info/'
      path: '/local-info'
      fullPath: '/local-info/'
      preLoaderRoute: typeof LocalInfoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-info/$slug': {
      id: '/local-info/$slug'
      path: '/local-info/$slug'
      fullPath: '/local-info/$slug'
      preLoaderRoute: typeof LocalInfoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/': {
      id: '/surveys/'
      path: '/surveys'
      fullPath: '/surveys/'
      preLoaderRoute: typeof SurveysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$slug': {
      id: '/surveys/$slug'
      path: '/surveys/$slug'
      fullPath: '/surveys/$slug'
      preLoaderRoute: typeof SurveysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$slug': {
      id: '/updates/$slug'
      path: '/updates/$slug'
      fullPath: '/updates/$slug'
      preLoaderRoute: typeof UpdatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  EventsSlugRoute: EventsSlugRoute,
  LocalInfoSlugRoute: LocalInfoSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  SurveysSlugRoute: SurveysSlugRoute,
  UpdatesSlugRoute: UpdatesSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  LocalInfoIndexRoute: LocalInfoIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SurveysIndexRoute: SurveysIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
