/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAppAppNameIndexRouteImport } from './routes/_shell.app.$appName.index'
import { Route as ShellAppAppNameSectionRouteImport } from './routes/_shell.app.$appName.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAppAppNameIndexRoute = ShellAppAppNameIndexRouteImport.update({
  id: '/app/$appName/',
  path: '/app/$appName/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppAppNameSectionRoute = ShellAppAppNameSectionRouteImport.update({
  id: '/app/$appName/$section',
  path: '/app/$appName/$section',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/$appName/$section': typeof ShellAppAppNameSectionRoute
  '/app/$appName/': typeof ShellAppAppNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$appName/$section': typeof ShellAppAppNameSectionRoute
  '/app/$appName': typeof ShellAppAppNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/app/$appName/$section': typeof ShellAppAppNameSectionRoute
  '/_shell/app/$appName/': typeof ShellAppAppNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app/$appName/$section' | '/app/$appName/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/$appName/$section' | '/app/$appName'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/app/$appName/$section'
    | '/_shell/app/$appName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/app/$appName/': {
      id: '/_shell/app/$appName/'
      path: '/app/$appName'
      fullPath: '/app/$appName/'
      preLoaderRoute: typeof ShellAppAppNameIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/$appName/$section': {
      id: '/_shell/app/$appName/$section'
      path: '/app/$appName/$section'
      fullPath: '/app/$appName/$section'
      preLoaderRoute: typeof ShellAppAppNameSectionRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAppAppNameSectionRoute: typeof ShellAppAppNameSectionRoute
  ShellAppAppNameIndexRoute: typeof ShellAppAppNameIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAppAppNameSectionRoute: ShellAppAppNameSectionRoute,
  ShellAppAppNameIndexRoute: ShellAppAppNameIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
