/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellActionsRouteImport } from './routes/_shell.actions'
import { Route as ShellApplicationsRouteImport } from './routes/_shell.applications'
import { Route as ShellInfrastructureRouteImport } from './routes/_shell.infrastructure'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellActionsRoute = ShellActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellApplicationsRoute = ShellApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInfrastructureRoute = ShellInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/actions': typeof ShellActionsRoute
  '/applications': typeof ShellApplicationsRoute
  '/infrastructure': typeof ShellInfrastructureRoute
}
export interface FileRoutesByTo {
  '/actions': typeof ShellActionsRoute
  '/applications': typeof ShellApplicationsRoute
  '/infrastructure': typeof ShellInfrastructureRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/actions': typeof ShellActionsRoute
  '/_shell/applications': typeof ShellApplicationsRoute
  '/_shell/infrastructure': typeof ShellInfrastructureRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/actions' | '/applications' | '/infrastructure'
  fileRoutesByTo: FileRoutesByTo
  to: '/actions' | '/applications' | '/infrastructure' | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/actions'
    | '/_shell/applications'
    | '/_shell/infrastructure'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/actions': {
      id: '/_shell/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ShellActionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/applications': {
      id: '/_shell/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ShellApplicationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/infrastructure': {
      id: '/_shell/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof ShellInfrastructureRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellActionsRoute: typeof ShellActionsRoute
  ShellApplicationsRoute: typeof ShellApplicationsRoute
  ShellInfrastructureRoute: typeof ShellInfrastructureRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellActionsRoute: ShellActionsRoute,
  ShellApplicationsRoute: ShellApplicationsRoute,
  ShellInfrastructureRoute: ShellInfrastructureRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
